// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmyxhvatodzgnesgdzxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1teXhodmF0b2R6Z25lc2dkenh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTIwMzEsImV4cCI6MjA2MzI2ODAzMX0.HRygIbGseTxlGsUCTlfDgFtv5hz3tU5rPlov39ZAsUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);